name: Android Build for Baaz Staff

on:
  push:
    branches:
      - ticket*

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 17 (pre-installed)
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"  # Using '17' since it's pre-installed

      - name: Set up Node.js (pre-installed)
        uses: actions/setup-node@v2
        with:
          node-version: "16"  # Pre-installed version is '16'

      - name: Install dependencies
        run: |
          npm install --save-dev jetifier
          npx jetifier
          npm install

      - name: Add Firebase App Distribution plugin to Fastlane
        run: sudo fastlane add_plugin firebase_app_distribution

      - name: Build APK for Baaz Staff
        run: fastlane android createApk
