name: Android Build for Baaz Staff

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  test-APK-build-and-distribute:
    if: startsWith(github.event.inputs.branch, 'ticket-') || github.event.inputs.branch == 'dev'
    uses: ./.github/workflows/distribute-to-firebase.yml

  production-build-and-deploy:
    if: github.event.inputs.branch == 'main'
    uses: ./.github/workflows/deploy-to-playstore.yml
