name: Android Build for Baaz Staff

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  release-apk-to-firebase-app-distribution:
    uses: ./.github/workflows/distribute-to-firebase.yml

  release-aab-to-play-store:
    uses: ./.github/workflows/deploy-to-playstore.yml
