name: Android Build for Baaz Staff

on:
    push:
        branches:
            - ticket*

    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to build'
                required: true
                default: 'main'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.branch }}

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  distribution: "adopt"
                  java-version: "17.0.10"

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16.17.1"

            - name: ruby
              uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
              with:
                  ruby-version: 2.6.10

            - name: Install Fastlane
              run: gem install fastlane

            - name: Install dependencies
              run: |
                  npm install --save-dev jetifier
                  npx jetifier
                  npm install

            - name: Adding plugin for Firebase App Distribution
              run: sudo fastlane add_plugin firebase_app_distribution

            - name: Create APK for Baaz Staff
              run: fastlane android createApk