name: Deploy to Play Store

on:
  workflow_call:

jobs:
  production-build-and-deploy:
    if: github.event.inputs.branch == 'main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set USERS_ALLOWED_TO_RUN_THE_PIPELINE
        env:
          USERS_ALLOWED_TO_RUN_THE_PIPELINE: ${{ vars.USERS_ALLOWED_TO_DEPLOY_IN_PROTECTED_BRANCH }}
        run: |
          echo "Checking if actor is allowed to run the pipeline..."
          ACTOR="${{ github.actor }}"
          USERS_ARRAY=$(echo $USERS_ALLOWED_TO_RUN_THE_PIPELINE | jq -r '.users_info[]')

          if echo "$USERS_ARRAY" | grep -q "^$ACTOR$"; then
              echo "Actor id is ${{github.actor_id}} and ${{github.actor}}"
              echo "Actor $ACTOR is allowed to run the pipeline."
          else
              echo "Actor $ACTOR is not allowed to run the pipeline."
              exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11 (pre-installed)
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Node.js (pre-installed)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install --save-dev jetifier
          npx jetifier
          npm install

      - name: Set up Ruby 2.7.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install Bundler
        run:  gem install bundler -v '2.1.4'

      - name: Install Fastlane using Bundler
        run:  bundle install

      - name: Adding plugin for Firebase App Distribution
        run: bundle exec fastlane add_plugin firebase_app_distribution

      - name: Build and Deploy to Production Environment
        run:  bundle exec fastlane playstoreInternal
        env:
          USER_EMAIL: ${{ github.actor_id }}
          USER_NAME: ${{ github.actor }}
          ALLOWED_USERS: ${{vars.USERS_ALLOWED_TO_DEPLOY_IN_PROTECTED_BRANCH}}

