name: Distribute to firebase

on:
  workflow_call:

jobs:
  test-APK-build-and-distribute:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up environment
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Set up JDK 11 (pre-installed)
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Node.js (pre-installed)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install --save-dev jetifier
          npx jetifier
          npm install

      - name: Set up Ruby 2.7.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install Bundler
        run: gem install bundler -v '2.1.4'

      - name: Install Fastlane using Bundler
        run: bundle install 

      - name: Adding plugin for Firebase App Distribution
        run: bundle exec fastlane add_plugin firebase_app_distribution

      - name: Bundle Update after installing firebase_app_distribution
        run: bundle update

      - name: Build and Distribute APK for Baaz Staff
        run: bundle exec fastlane createApk
        env:
          BRANCH_NAME: ${{ github.event.inputs.branch }}
          BUILD_TYPE: ${{ github.event.inputs.environment }}
