name: Distribute to firebase

on:
  workflow_call:

jobs:
  test-APK-build-and-distribute:
    if: startsWith(github.event.inputs.branch, 'ticket-') || github.event.inputs.branch == 'dev'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11 (pre-installed)
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Node.js (pre-installed)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install --save-dev jetifier
          npx jetifier
          npm install

      - name: Install Bundler
        run: sudo gem install bundler -v '~> 2.0'

      - name: Install Fastlane using Bundler
        run: sudo bundle install --path vendor/bundle

      - name: Adding plugin for Firebase App Distribution
        run: sudo fastlane add_plugin firebase_app_distribution

      - name: Build and Distribute APK for Baaz Staff
        run: fastlane createApk
