name: IOS Build for Baaz Staff

on:
  workflow_dispatch:
      inputs:
          branch:
              description: 'Branch to build'
              required: true
              default: 'dev'
          environment:
              description: 'Select the build type'
              required: true
              type: choice
              options:
              - staging
              - production
              - development

jobs:
  release-apk-to-firebase-app-distribution:
        if: startsWith(github.event.inputs.branch, 'main') || github.event.inputs.branch == 'main'
        uses: ./.github/workflows/distribute-to-firebase.yml


